# Debug inputs
#        flogo_project_name: "MLE_Send-EMS-Msg"
# flogo_project_description: ""
#                   repoUrl: "github.com?owner=MLEIJDEK&repo=flogo"
# flogo_ems_queue_receivers: []
#   flogo_ems_queue_senders: ["MLE_Demo"]
#            flogo_task_ids: ["StartActivity","EMSSendMessage","ConfigureHTTPResponse","ReplyToTrigger"]
#               flogo_tasks: [{"id":"StartActivity","name":"StartActivity","description":"NoOp Activity","activity":{"ref":"#noop"}},{"id":"EMSSendMessage","name":"EMSSendMessage","description":"","activity":{"ref":"#sendmessage","settings":{"connection":"conn://43a40201-5d92-40a1-a884-157031567b36","destinationType":"Queue","settingDestination":"MLE_Demo","deliveryDelay":0},"input":{"message":"=$flow.body.inputMessage","destination":""},"schemas":{"input":{"headers":{"type":"json","value":"{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"type\":\"object\",\"properties\":{\"correlationID\":{\"type\":\"string\"},\"replyTo\":{\"type\":\"string\"},\"deliveryMode\":{\"type\":\"string\"},\"expiration\":{\"type\":\"integer\"},\"priority\":{\"type\":\"integer\"}}}","fe_metadata":"{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"type\":\"object\",\"properties\":{\"correlationID\":{\"type\":\"string\"},\"replyTo\":{\"type\":\"string\"},\"deliveryMode\":{\"type\":\"string\"},\"expiration\":{\"type\":\"integer\"},\"priority\":{\"type\":\"integer\"}}}","feSchemaMap":{}}}}}},{"id":"ConfigureHTTPResponse","name":"ConfigureHTTPResponse","description":"Configure HTTP Response Activity","activity":{"ref":"#httpresponse","input":{"trigger":"ReceiveHTTPMessage","responsecode":"200","input":{"mapping":{"body":{"response":"=$activity[EMSSendMessage].messageId"}}}},"schemas":{"input":{"input":{"type":"json","value":"{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"type\":\"object\",\"properties\":{\"body\":{\"type\":\"object\",\"properties\":{\"response\":{\"type\":\"string\"}}}}}","fe_metadata":"{\"body\":{\"response\":\"string\"}}","feSchemaMap":{}}},"output":{"response":{"type":"json","value":"{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"type\":\"object\",\"properties\":{\"body\":{\"type\":\"object\",\"properties\":{\"response\":{\"type\":\"string\"}}}}}","fe_metadata":"{\"body\":{\"response\":\"string\"}}","feSchemaMap":{}}}}}},{"id":"ReplyToTrigger","name":"ReplyToTrigger","description":"Reply back to the trigger and continue flow execution, it must be used only in the flow with the trigger configured.","activity":{"ref":"#actreply","input":{"reply":{"mapping":{"code":"=$activity[ConfigureHTTPResponse].code","responseBody":"=$activity[ConfigureHTTPResponse].response"}}},"schemas":{"input":{"reply":{"type":"json","value":"{\"type\":\"object\",\"title\":\"Inputs\",\"properties\":{\"code\":{\"type\":\"integer\",\"required\":false},\"responseBody\":{\"type\":\"object\",\"properties\":{\"body\":{\"type\":\"any\"},\"headers\":{\"type\":\"object\"}}}},\"required\":[]}","fe_metadata":"{\"type\":\"object\",\"title\":\"Inputs\",\"properties\":{\"code\":{\"type\":\"integer\",\"required\":false},\"responseBody\":{\"type\":\"object\",\"properties\":{\"body\":{\"type\":\"any\"},\"headers\":{\"type\":\"object\"}}}},\"required\":[]}","feSchemaMap":{}}}}}}]
#                     owner: "user:default/michel.leijdekker"
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: WS_Send-EMS-Msg_FLOGO_APP
    tags:
      - flogo-app
      - platform
    tibcoPlatformApps:
      - appType: flogo
        appName: WS_Send-EMS-Msg
        dataPlaneName: DP4_PresalesNL
        dpId: cq1duk2jcp26pefl1d60
        capabilityInstanceId: cq1ekso6c9lo9im24qlg
        appId: cume07a7s9bmf6nsijbg
    links:
      - title: TIBCO Flogo Enterprise
        url: https://docs.tibco.com/products/tibco-flogo-enterprise
      - title: Deployed Application
        url: https://tibcoatseuwe1.eu-west.my.tibco.com/cp/flogo/appdetails/endpoints?dp_id=cq1duk2jcp26pefl1d60&capability_instance_id=cq1ekso6c9lo9im24qlg&app_id=crps614bp2ppslobqc00
    annotations:
      github.com/project-slug: https://github.com/MLEIJDEK/flogo
      backstage.io/techdocs-ref: dir:.
spec:
    type: flogo
    lifecycle: development
    owner: user:default/michel.leijdekker
    dependsOn:
      - resource:default/Workshop_Topic_EMS_TOPIC
      - resource:default/WS_Send-EMS-Msg_StartActivity_FLOGO_TASK
      - resource:default/WS_Send-EMS-Msg_EMSSendMessage_FLOGO_TASK
      - resource:default/WS_Send-EMS-Msg_ConfigureHTTPResponse_FLOGO_TASK
      - resource:default/WS_Send-EMS-Msg_ReplyToTrigger_FLOGO_TASK

