apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: MLE_CountryFlogo
  description: ''
  tags:
    - flogo
  links:
    - title: TIBCO Flogo Enterprise
      url: https://docs.tibco.com/products/tibco-flogo-enterprise
  annotations:
    github.com/project-slug: https://github.com/MLEIJDEK/flogo
    backstage.io/techdocs-ref: dir:.
spec:
  type: flogo
  lifecycle: development
  owner: user:default/michel.leijdekker
